### ISSUE TITLE
Usage as background video

### ISSUE THREAD

**Issue by pors** [t-obi/react-video-cover#159]
Hi @t-obi! Awesome project!

I'm interested in using it as a background video (with other content on a layer above it), like here is done for an image:

```
<div class="hero" style="background: url(images/hero.jpg') center center / cover">
  <div class="outer-container">
    <div class="container">
      <div class="inner-container">
      Blah blah
      </div>
    </div>
  </div>
</div>
```

So here the "Blah blah" is show on top of the image. Is this possible with your video component in some way?

Cheers!

**Comment by t-obi** [comment]
Hey,
thanks for the kind words.

The second example is pretty much what you are describing: http://www.kloht.com/react-video-cover/#/background

The source is over here: https://github.com/t-obi/react-video-cover/blob/master/examples/BackgroundCoverExample.js

Basically it renders the video with fixed position to fill the page, with a negative z-index so that your content would be visible above it.
I think there might be different approaches to implement this, but yes it should definitely be possible. You can't pass any children at the moment though. Actually that might be a good idea to add - I'll think about it.

**Comment by pors** [comment]
Thanks for the quick answer!

Maybe it can also be done without any changes, just using CSS, have a look at this: https://jsfiddle.net/cwells/7req2mdd/

**Comment by t-obi** [comment]
That jsfiddle didn't use object-fit: cover, I have edited it slightly: https://jsfiddle.net/tkloht/y61s3vqk/3/

You can have that same effect with react-video-cover, check out this repo which is pretty much copy/paste from the jsfiddle and replaced the <video/> with object-fit-cover: https://github.com/t-obi/background-video-example. The relevant code is in src/App.js, some styles in src/index.css. You can see the result over here: http://www.kloht.com/background-video-example/

hope that helps :)

**Comment by pors** [comment]
Thanks a lot Tobias!
